{% set name = "datachain" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datachain-{{ version }}.tar.gz
  sha256: 0d56f010fa5bd059537ebb10854d382365ea8bb2939e043a90177f64f35a2b05

build:
  entry_points:
    - datachain = datachain.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - setuptools-scm >=6.3.1
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - tomlkit
    - tqdm
    - numpy >=1,<3
    - pandas >=2.0.0
    - pyarrow
    - typing_extensions
    - python-dateutil >=2
    - attrs >=21.3.0
    - s3fs >=2024.2.0
    - gcsfs >=2024.2.0
    - adlfs >=2024.2.0
    - dvc-data >=3.10,<4
    - dvc-objects >=4,<6
    - shtab >=1.3.4,<2
    - sqlalchemy >=2
    - multiprocess ==0.70.16
    - cloudpickle
    - orjson >=3.10.5
    - pydantic >=2,<3
    - jmespath >=1.0
    - datamodel-code-generator >=0.25
    - pillow >=10.0.0,<12
    - msgpack-python >=1.0.4,<2
    - psutil
    - huggingface_hub
    - iterative-telemetry >=0.0.9
    - platformdirs
    - dvc-studio-client >=0.21,<1
    - tabulate

test:
  imports:
    - datachain
  commands:
    - pip check
    - datachain --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iterative/datachain
  doc_url: https://docs.datachain.ai/
  summary: Wrangle unstructured AI data at scale
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
